#!/data/data/com.termux/files/usr/bin/bash

WEBHOOK_URL="https://discord.com/api/webhooks/1484573967997206678/Tpix_g8c4U-uaknycIFNUZ3t5UN26rzOq6DNimebAjecDtAdDzwJhAXLZUKRcfwAzZXF"

# ===== SERVER GROUP PRESETS =====

GROUP_1_NAME="Hopper-1"
GROUP_1_SERVERS="
https://www.roblox.com/share?code=fc536ec6ccaaf844866b3a0e50154b5f&type=Server
https://www.roblox.com/share?code=c9d091e6625eea408ede5ddd035e0d6d&type=Server
https://www.roblox.com/share?code=ed67a53d79531048a02f03f33ed7fb94&type=Server
https://www.roblox.com/share?code=0d23492e13741c47ab282846cb213375&type=Server
https://www.roblox.com/share?code=4890256a940c7c4fbe0300494f656fa7&type=Server
https://www.roblox.com/share?code=b56011252594ed408f0bb384260c5c69&type=Server
https://www.roblox.com/share?code=b889fbd03aebc043a723019cc3e8cb9b&type=Server
https://www.roblox.com/share?code=1bf66f88c8649046a47668bfada3f518&type=Server
https://www.roblox.com/share?code=014bf5cf2628014dbbbc2c0629dc1731&type=Server
https://www.roblox.com/share?code=5af2fa72c89d5d42a84f6104d33a0eb3&type=Server
https://www.roblox.com/share?code=3c5e68a52bd5314b9e2d1b28111a45ce&type=Server
https://www.roblox.com/share?code=093f79297be0114cbdd881011d1ec830&type=Server
"

GROUP_2_NAME="Hopper-2"
GROUP_2_SERVERS="
https://www.roblox.com/share?code=f3a45e8a2a98794b94ed47efc13584b7&type=Server
https://www.roblox.com/share?code=fce7ac20cb337f4abc9d5c68d66b833f&type=Server
https://www.roblox.com/share?code=9095848cfd9ee140878d00afd8711289&type=Server
https://www.roblox.com/share?code=5657e37d908bc740bc58fdcba8a5e915&type=Server
https://www.roblox.com/share?code=5fd700fe68a78d42b070f9119531ab89&type=Server
https://www.roblox.com/share?code=eee96b8c09242a43976341a812b5168c&type=Server
https://www.roblox.com/share?code=a552731af246f4459bf978101c997d58&type=Server
https://www.roblox.com/share?code=469b6828f1f33a44b3447b63842b7e4e&type=Server
https://www.roblox.com/share?code=7ed6c0b491e56347b032bd1321b0195c&type=Server
https://www.roblox.com/share?code=6fee648fbcaaf74099f9022c98dfe928&type=Server
https://www.roblox.com/share?code=eee0d4f07caeb546a01b7c8471ce3e25&type=Server
https://www.roblox.com/share?code=20e00000b868414d8ce81f5ab33de8e8&type=Server
"

GROUP_3_NAME="Hopper-3"
GROUP_3_SERVERS="
https://www.roblox.com/share?code=3b20effa0af43e429386132d0f8e5053&type=Server
https://www.roblox.com/share?code=f055cc9812ad754382681ea4051a47bb&type=Server
https://www.roblox.com/share?code=9f2ca192dc8c6242a6270b96690a904f&type=Server
https://www.roblox.com/share?code=a8f1760fa83c6d48b6184ac1040b5300&type=Server
https://www.roblox.com/share?code=dce7f23609543b4da817c3c7805fabef&type=Server
https://www.roblox.com/share?code=e9359f25dabc19429426cf86f4300b01&type=Server
https://www.roblox.com/share?code=7e8d04a7b83f814781b29f8764b68746&type=Server
https://www.roblox.com/share?code=01d440f0d78cfc4da890c5f688614b11&type=Server
https://www.roblox.com/share?code=cafa35ce5103f04784afae02f923bddd&type=Server
https://www.roblox.com/share?code=2e4b5f50ce70d04690f864d8397d5ef3&type=Server
https://www.roblox.com/share?code=6255c7ce2013734e954818a2b2f4791a&type=Server
https://www.roblox.com/share?code=ecb96b579d0e004a9e897f88f5d03417&type=Server
"

GROUP_4_NAME="Hopper-4"
GROUP_4_SERVERS="
https://www.roblox.com/share?code=d79ff9464471e54582b29cd5731a2e55&type=Server
https://www.roblox.com/share?code=9173d2a8b195e84f8ca4eff8263cdee0&type=Server
https://www.roblox.com/share?code=915b745949795f43bdb0441656870436&type=Server
https://www.roblox.com/share?code=acc5cb9698f0a94c8cd03437b8c672a8&type=Server
https://www.roblox.com/share?code=2bade7225d2d61498a11813aad3be25d&type=Server
https://www.roblox.com/share?code=a73fff8ffb58494a8bf6bc25581137de&type=Server
https://www.roblox.com/share?code=4a93c440d741304d8738e5d08af5e85a&type=Server
https://www.roblox.com/share?code=642b436828fea0408f186e7d4e2f5109&type=Server
https://www.roblox.com/share?code=ebbade1cd0bfc04a8738a211d7e2ad7d&type=Server
https://www.roblox.com/share?code=031388fe069cf64eab9e8d3f846b9e0c&type=Server
https://www.roblox.com/share?code=7d6000f9a94781428ec35c3cfd6d038b&type=Server
https://www.roblox.com/share?code=ed9f01dedef6ce4fa6ddf560360951c7&type=Server
"

GROUP_5_NAME="Hopper-5"
GROUP_5_SERVERS="
https://www.roblox.com/share?code=707f3e7e9c04fb45af139666d8158e72&type=Server
https://www.roblox.com/share?code=b76e06f5451e654c803b43e884472d1e&type=Server
https://www.roblox.com/share?code=78bb1dddb8ad5f4b8933a2a4bee4761f&type=Server
https://www.roblox.com/share?code=dd72eae4f6e4a7459ffc3d202e459bc8&type=Server
https://www.roblox.com/share?code=7b7021edd12a5742b42419813f74b98f&type=Server
https://www.roblox.com/share?code=bd98b8f8ceea734498f40bc125d3e511&type=Server
https://www.roblox.com/share?code=f9e3adab13ab2f4f87ad0fbcf5cbb883&type=Server
https://www.roblox.com/share?code=830e09c2a953434790f2627f044f19df&type=Server
https://www.roblox.com/share?code=99b6cbaaa3293f42b1541d12c7429cba&type=Server
https://www.roblox.com/share?code=7a502abf37799f4080ad28e8900f8629&type=Server
https://www.roblox.com/share?code=24dbe380b9d45a43960500909887a41c&type=Server
https://www.roblox.com/share?code=0194257234240e46881b3184720229db&type=Server
"

GROUP_6_NAME="Hopper-6"
GROUP_6_SERVERS="
https://www.roblox.com/share?code=fca8f99df73d48499f2827ba112083c6&type=Server
https://www.roblox.com/share?code=84ddf1e8531a424c9dad4c432a697eae&type=Server
https://www.roblox.com/share?code=7bd2773e255f69498bf478a5e9e60df2&type=Server
https://www.roblox.com/share?code=75374d26bc05fb4d86cb3d16a1a162dd&type=Server
https://www.roblox.com/share?code=fcae0eab0beab04bae65ec55cc53d584&type=Server
https://www.roblox.com/share?code=790da38838000c4694a7b649bd1f9233&type=Server
https://www.roblox.com/share?code=2625ceec240e8a48a82beda495a7b2a3&type=Server
https://www.roblox.com/share?code=cbb83376e623d24f97ca0bdd39040f74&type=Server
https://www.roblox.com/share?code=9e4dfbb2ee09d942961e3529476ba4e2&type=Server
https://www.roblox.com/share?code=3bd65ee463f5b5458a0d1fadba3dd3f5&type=Server
https://www.roblox.com/share?code=d931ca3a214f8a4788685ceed60d4879&type=Server
https://www.roblox.com/share?code=a44c282d12b4ca4f9fca6821a04aeb00&type=Server
https://www.roblox.com/share?code=b7ade93233701246b3e48a34563ddedb&type=Server
"

GROUP_7_NAME="Hopper-7"
GROUP_7_SERVERS="
https://www.roblox.com/share?code=340687815ff27648ab91e1de7bfab130&type=Server
https://www.roblox.com/share?code=fb4fa677d2e03140bf9bfb5a1c0d7621&type=Server
https://www.roblox.com/share?code=3f41369807fa28428989cd0b19a7bcd3&type=Server
https://www.roblox.com/share?code=9c7befe094a62b4385ad2d2cff539a45&type=Server
https://www.roblox.com/share?code=04218d00b5f7074bae849b60030b85a0&type=Server
https://www.roblox.com/share?code=d1b2448c864e3d468b75421ec899776e&type=Server
https://www.roblox.com/share?code=103b90743503c449a21095f264514166&type=Server
https://www.roblox.com/share?code=081d2854b29f2045bdd31353f7d40293&type=Server
https://www.roblox.com/share?code=92f61b5fb70a2541bf5573b57f2fd9a5&type=Server
https://www.roblox.com/share?code=6fc4144d5ed05b4fa8bd3edf682b3f40&type=Server
https://www.roblox.com/share?code=dab883134f48844c814b24975cd78589&type=Server
https://www.roblox.com/share?code=69815c56ca587a45bdddafcfa099df4a&type=Server
"

GROUP_8_NAME="Hopper-8"
GROUP_8_SERVERS="
https://www.roblox.com/share?code=a1becc31dcb9e14dbe5f9fa222e50ec0&type=Server
https://www.roblox.com/share?code=16086c0eb6c82a43bc873ff90b1593f0&type=Server
https://www.roblox.com/share?code=8e32b8bdedd8774e968c7d1973100418&type=Server
https://www.roblox.com/share?code=89452930d1f408498bc464ee90b48546&type=Server
https://www.roblox.com/share?code=029b1025266c5045bff264c5bcf0a1c3&type=Server
https://www.roblox.com/share?code=530bce6d5d13324ca07374f8ab302fa8&type=Server
https://www.roblox.com/share?code=66ba406e2736b9459933f38c95c19126&type=Server
https://www.roblox.com/share?code=5c5e495ea8f06d4f943f43515ca89e6c&type=Server
https://www.roblox.com/share?code=c9b5ed981053f846b83fd00cffaf9c26&type=Server
https://www.roblox.com/share?code=aa4d2967f803b54ea2db031569c0bcf5&type=Server
https://www.roblox.com/share?code=9bf1b6e12cd4ec4a8129e182ee3c177b&type=Server
https://www.roblox.com/share?code=9d3b50eb210dd5409a269a89810b4e59&type=Server
"

GROUP_9_NAME="Hopper-9"
GROUP_9_SERVERS="
https://www.roblox.com/share?code=3c5086c314789e4fa6cba22365297324&type=Server
https://www.roblox.com/share?code=c8461aed1ca7214bb39bf25658da1f71&type=Server
https://www.roblox.com/share?code=938bd344be5c8540a9a93342f9ac43d5&type=Server
https://www.roblox.com/share?code=da35f131d358214ca1fe853ce750016a&type=Server
https://www.roblox.com/share?code=a69d2463d5a8b946b285d85ada986132&type=Server
https://www.roblox.com/share?code=f66a544a49e1284c8cf54aa6dd063904&type=Server
https://www.roblox.com/share?code=9840d68e35d6834aa0f4fd5d0d0a5c2a&type=Server
https://www.roblox.com/share?code=cb0c8ea50712834c9f9e130dc1d7f35c&type=Server
https://www.roblox.com/share?code=bfa36298647d1745b6524c0c175e7cb7&type=Server
https://www.roblox.com/share?code=5057498e02439d4bbf01186958863829&type=Server
https://www.roblox.com/share?code=272535803c522f42b216c3daeac96c9d&type=Server
https://www.roblox.com/share?code=dd095320549ca64bae23c6b4a288370c&type=Server
"

GROUP_10_NAME="Hopper-10"
GROUP_10_SERVERS="
https://www.roblox.com/share?code=41eebfa30dff5b48a7813b7a5fc92359&type=Server
https://www.roblox.com/share?code=0110500be229f4499e6ea4a3a973af8d&type=Server
https://www.roblox.com/share?code=c0a25739fa7d1a4aad026c5fc6ab0cc9&type=Server
https://www.roblox.com/share?code=6e2a5bb951487c448d08fd04587d9df5&type=Server
https://www.roblox.com/share?code=742dffa59303e14ab5e8041af8fc268b&type=Server
https://www.roblox.com/share?code=c7298fe6229e804d8d4dec93f688d7ea&type=Server
https://www.roblox.com/share?code=73b8d4ab8a2de34d81f72a2ffc85f467&type=Server
https://www.roblox.com/share?code=1270ffcdfdbfb746b6a812735751130a&type=Server
https://www.roblox.com/share?code=9e1da6c946c29b44b50000b5d1e488c1&type=Server
https://www.roblox.com/share?code=8b7417b278721144a6e36eef46174920&type=Server
https://www.roblox.com/share?code=9d5e813a50433843a1435d2819c45f6f&type=Server
https://www.roblox.com/share?code=55b207aacf695447a81548825e50cdff&type=Server
"

GROUP_11_NAME="Hopper-11"
GROUP_11_SERVERS="
https://www.roblox.com/share?code=006626b5663da749b9b5e12957fdef44&type=Server
https://www.roblox.com/share?code=a2ac77a2fa3a3c48b8dcea71deb6dd7a&type=Server
https://www.roblox.com/share?code=f3ca51f023881440ac955404812590c0&type=Server
https://www.roblox.com/share?code=b58e0eca10f0df428be69da9ff28406b&type=Server
https://www.roblox.com/share?code=1a8665a787c25545bc4bda68b34d5f51&type=Server
https://www.roblox.com/share?code=d25df99f0234204d8213d797421da886&type=Server
https://www.roblox.com/share?code=4c4851dbcf3527418da94276b931a65d&type=Server
https://www.roblox.com/share?code=78d5e93f850a084a94aee7c0cfea589e&type=Server
https://www.roblox.com/share?code=82e476945d634e4cab00df497f5df17a&type=Server
https://www.roblox.com/share?code=bbb4202626bc2249ab7b039f29d605b5&type=Server
https://www.roblox.com/share?code=fdbe4ab807567b4f95421e665e67c405&type=Server
https://www.roblox.com/share?code=bf1119991b6de44095f6d723c0c36b8f&type=Server
"

GROUP_12_NAME="Hopper-12"
GROUP_12_SERVERS="
https://www.roblox.com/share?code=9d430625095abd41a390ee14e993ab91&type=Server
https://www.roblox.com/share?code=a87f46db0794924795d143f47dae7999&type=Server
https://www.roblox.com/share?code=1a7b245fc383834eb3b3e294cb337efa&type=Server
https://www.roblox.com/share?code=d0b36c7ef94bf74389e474d6a66246f6&type=Server
https://www.roblox.com/share?code=7df700fa73397f46961ccd28a96cf2b9&type=Server
https://www.roblox.com/share?code=892b3ea57b06cc4aafff449d82e7f5d4&type=Server
https://www.roblox.com/share?code=9f6e5cc1f2db8743804fa8ec19e5b9f2&type=Server
https://www.roblox.com/share?code=4556ea388f0119429c3c44bcf8d5125c&type=Server
https://www.roblox.com/share?code=ee179a474958844ca85a66d4bc981512&type=Server
https://www.roblox.com/share?code=c89d6496c95c6a49aeb78461c8976f53&type=Server
https://www.roblox.com/share?code=b34ea84a1d77814a9a57ea6c70d4ae94&type=Server
https://www.roblox.com/share?code=c2c468962aeccd4386c7cfc6563c0c95&type=Server
"

GROUP_13_NAME="Hopper-13"
GROUP_13_SERVERS="
https://www.roblox.com/share?code=3162f6d7210b114787c3e9bfbb00f585&type=Server
https://www.roblox.com/share?code=aebf14e70238dd4b9f95f643f99a2b8f&type=Server
https://www.roblox.com/share?code=3eff5ba090b99a40a2963330e33d7e84&type=Server
https://www.roblox.com/share?code=9a15c0fa838fc64398853bc493ca0660&type=Server
https://www.roblox.com/share?code=20a57e876ee2d14688d078ab10c70ae6&type=Server
https://www.roblox.com/share?code=0e58f551c96fdc42bce23400a7f5882a&type=Server
https://www.roblox.com/share?code=29e465572051a847a53ab0cc41890e5b&type=Server
https://www.roblox.com/share?code=5d0c79f7c23c6f42bd0522c0e9e3d0d2&type=Server
https://www.roblox.com/share?code=6e015014c542db4aa73d8c1fa9ba84bd&type=Server
https://www.roblox.com/share?code=2c1dbef26d4795489d32e5b9c2a2986b&type=Server
https://www.roblox.com/share?code=08d034012797934bb544a6bd0a1221e7&type=Server
https://www.roblox.com/share?code=e3372ef2c72b614eb25074d8fc3ff069&type=Server
"

GROUP_14_NAME="Hopper-14"
GROUP_14_SERVERS="
https://www.roblox.com/share?code=c61ee4dd39f50848a1bd04f1e462faa5&type=Server
https://www.roblox.com/share?code=d53d2a2db76110498569c6945ba99df4&type=Server
https://www.roblox.com/share?code=b19201388485f0488d91d86fc29d27e2&type=Server
https://www.roblox.com/share?code=dd913b9d1b504b49bcf93c4d8b95f034&type=Server
https://www.roblox.com/share?code=8e5b07fb7eb0c044a2018d7d8cc160fc&type=Server
https://www.roblox.com/share?code=866797443c13c04d883cd810bc7a21e1&type=Server
https://www.roblox.com/share?code=3b3bcd1be96e734fb5a1eb00c2dd4530&type=Server
"
# ===== SELECT GROUP (INTERACTIVE) =====

while true; do
  echo "Select a group to run:"
  echo "1) $GROUP_1_NAME"
  echo "2) $GROUP_2_NAME"
  echo "3) $GROUP_3_NAME"
  echo "4) $GROUP_4_NAME"
  echo "5) $GROUP_5_NAME"
  echo "6) $GROUP_6_NAME"
  echo "7) $GROUP_7_NAME"
  echo "8) $GROUP_8_NAME"
  echo "9) $GROUP_9_NAME"
  echo "10) $GROUP_10_NAME"
  echo "11) $GROUP_11_NAME"
  echo "12) $GROUP_12_NAME"
  echo "13) $GROUP_13_NAME"
  echo "14) $GROUP_14_NAME"

  read -p "Enter group number (1-14): " ACTIVE_GROUP

  if [[ "$ACTIVE_GROUP" =~ ^[1-14]$ ]]; then
    break
  else
    echo "Invalid input. Try again."
  fi
done

# ===== VALIDATION =====

GROUP_NAME_VAR="GROUP_${ACTIVE_GROUP}_NAME"
GROUP_SERVERS_VAR="GROUP_${ACTIVE_GROUP}_SERVERS"

if [ -z "${!GROUP_NAME_VAR}" ]; then
  echo "Invalid ACTIVE_GROUP ($ACTIVE_GROUP). Defaulting to Group 1."
  ACTIVE_GROUP=1
  GROUP_NAME_VAR="GROUP_1_NAME"
  GROUP_SERVERS_VAR="GROUP_1_SERVERS"
fi

# ===== LOAD SELECTED GROUP =====

GROUP_NAME="${!GROUP_NAME_VAR}"
servers_raw="${!GROUP_SERVERS_VAR}"

readarray -t servers < <(printf "%s\n" "$servers_raw" | sed '/^\s*$/d')

# ===== WEBHOOK FUNCTION =====

send_webhook() {
  local message="$1"

  curl --max-time 5 -H "Content-Type: application/json" \
  -X POST \
  -d "$(printf '{"content":"%s"}' "$message")" \
  "$WEBHOOK_URL" > /dev/null 2>&1
}

total=${#servers[@]}

echo "Loaded $total servers from [$GROUP_NAME]"
send_webhook "**[$GROUP_NAME]** 🚀 Started with $total servers"

# ===== MAIN LOOP =====

while true; do
  index=1
  for server in "${servers[@]}"; do
    echo "Switching to ($index/$total)"
    echo "DEBUG: $server"

    send_webhook "**[$GROUP_NAME]** 🔄 Switching server **($index/$total)**"

    am start -a android.intent.action.MAIN -c android.intent.category.HOME
    sleep 2

    MAX_RETRIES=3
    joined=false

    for ((i=1; i<=MAX_RETRIES; i++)); do
      echo "Attempt $i to join server"

      am start -a android.intent.action.VIEW -d "$server"
      sleep 8

      current_app=$(dumpsys activity activities | grep mResumedActivity)

      if echo "$current_app" | grep -qi "com.roblox.client"; then
        echo "Roblox detected ✅"
        joined=true
        break
      else
        echo "Join failed ❌ retrying..."
        sleep 3
      fi
    done

    if [ "$joined" = true ]; then
      send_webhook "**[$GROUP_NAME]** ✅ Joined server **($index/$total)**"
    else
      send_webhook "**[$GROUP_NAME]** ❌ Failed to join server **($index/$total)**"
    fi

    sleep 420
    index=$((index+1))
  done
done
