#!/data/data/com.termux/files/usr/bin/bash
# Android / Termux server launcher. See Hopper.README.md.

# ===== SERVER GROUP PRESETS =====

GROUP_1_NAME="Hopper-1"
GROUP_1_SERVERS="
https://www.roblox.com/share?code=340687815ff27648ab91e1de7bfab130&type=Server
https://www.roblox.com/share?code=fb4fa677d2e03140bf9bfb5a1c0d7621&type=Server
https://www.roblox.com/share?code=3f41369807fa28428989cd0b19a7bcd3&type=Server
https://www.roblox.com/share?code=9c7befe094a62b4385ad2d2cff539a45&type=Server
https://www.roblox.com/share?code=04218d00b5f7074bae849b60030b85a0&type=Server
https://www.roblox.com/share?code=d1b2448c864e3d468b75421ec899776e&type=Server
https://www.roblox.com/share?code=103b90743503c449a21095f264514166&type=Server
https://www.roblox.com/share?code=081d2854b29f2045bdd31353f7d40293&type=Server
https://www.roblox.com/share?code=92f61b5fb70a2541bf5573b57f2fd9a5&type=Server
https://www.roblox.com/share?code=6fc4144d5ed05b4fa8bd3edf682b3f40&type=Server
https://www.roblox.com/share?code=dab883134f48844c814b24975cd78589&type=Server
https://www.roblox.com/share?code=69815c56ca587a45bdddafcfa099df4a&type=Server
https://www.roblox.com/share?code=a1becc31dcb9e14dbe5f9fa222e50ec0&type=Server
https://www.roblox.com/share?code=16086c0eb6c82a43bc873ff90b1593f0&type=Server
https://www.roblox.com/share?code=8e32b8bdedd8774e968c7d1973100418&type=Server
https://www.roblox.com/share?code=89452930d1f408498bc464ee90b48546&type=Server
https://www.roblox.com/share?code=029b1025266c5045bff264c5bcf0a1c3&type=Server
https://www.roblox.com/share?code=530bce6d5d13324ca07374f8ab302fa8&type=Server
https://www.roblox.com/share?code=66ba406e2736b9459933f38c95c19126&type=Server
https://www.roblox.com/share?code=5c5e495ea8f06d4f943f43515ca89e6c&type=Server
https://www.roblox.com/share?code=c9b5ed981053f846b83fd00cffaf9c26&type=Server
https://www.roblox.com/share?code=aa4d2967f803b54ea2db031569c0bcf5&type=Server
https://www.roblox.com/share?code=9bf1b6e12cd4ec4a8129e182ee3c177b&type=Server
https://www.roblox.com/share?code=9d3b50eb210dd5409a269a89810b4e59&type=Server
https://www.roblox.com/share?code=3c5086c314789e4fa6cba22365297324&type=Server
https://www.roblox.com/share?code=c8461aed1ca7214bb39bf25658da1f71&type=Server
https://www.roblox.com/share?code=938bd344be5c8540a9a93342f9ac43d5&type=Server
https://www.roblox.com/share?code=da35f131d358214ca1fe853ce750016a&type=Server
https://www.roblox.com/share?code=a69d2463d5a8b946b285d85ada986132&type=Server
https://www.roblox.com/share?code=f66a544a49e1284c8cf54aa6dd063904&type=Server
https://www.roblox.com/share?code=9840d68e35d6834aa0f4fd5d0d0a5c2a&type=Server
https://www.roblox.com/share?code=cb0c8ea50712834c9f9e130dc1d7f35c&type=Server
https://www.roblox.com/share?code=bfa36298647d1745b6524c0c175e7cb7&type=Server
https://www.roblox.com/share?code=5057498e02439d4bbf01186958863829&type=Server
https://www.roblox.com/share?code=272535803c522f42b216c3daeac96c9d&type=Server
https://www.roblox.com/share?code=dd095320549ca64bae23c6b4a288370c&type=Server
https://www.roblox.com/share?code=41eebfa30dff5b48a7813b7a5fc92359&type=Server
https://www.roblox.com/share?code=0110500be229f4499e6ea4a3a973af8d&type=Server
https://www.roblox.com/share?code=c0a25739fa7d1a4aad026c5fc6ab0cc9&type=Server
https://www.roblox.com/share?code=6e2a5bb951487c448d08fd04587d9df5&type=Server
https://www.roblox.com/share?code=742dffa59303e14ab5e8041af8fc268b&type=Server
https://www.roblox.com/share?code=c7298fe6229e804d8d4dec93f688d7ea&type=Server
https://www.roblox.com/share?code=73b8d4ab8a2de34d81f72a2ffc85f467&type=Server
https://www.roblox.com/share?code=1270ffcdfdbfb746b6a812735751130a&type=Server
https://www.roblox.com/share?code=9e1da6c946c29b44b50000b5d1e488c1&type=Server
https://www.roblox.com/share?code=8b7417b278721144a6e36eef46174920&type=Server
https://www.roblox.com/share?code=9d5e813a50433843a1435d2819c45f6f&type=Server
https://www.roblox.com/share?code=55b207aacf695447a81548825e50cdff&type=Server
https://www.roblox.com/share?code=006626b5663da749b9b5e12957fdef44&type=Server
https://www.roblox.com/share?code=a2ac77a2fa3a3c48b8dcea71deb6dd7a&type=Server
https://www.roblox.com/share?code=f3ca51f023881440ac955404812590c0&type=Server
https://www.roblox.com/share?code=b58e0eca10f0df428be69da9ff28406b&type=Server
https://www.roblox.com/share?code=1a8665a787c25545bc4bda68b34d5f51&type=Server
https://www.roblox.com/share?code=d25df99f0234204d8213d797421da886&type=Server
https://www.roblox.com/share?code=4c4851dbcf3527418da94276b931a65d&type=Server
https://www.roblox.com/share?code=78d5e93f850a084a94aee7c0cfea589e&type=Server
https://www.roblox.com/share?code=82e476945d634e4cab00df497f5df17a&type=Server
https://www.roblox.com/share?code=bbb4202626bc2249ab7b039f29d605b5&type=Server
https://www.roblox.com/share?code=fdbe4ab807567b4f95421e665e67c405&type=Server
https://www.roblox.com/share?code=bf1119991b6de44095f6d723c0c36b8f&type=Server
"

GROUP_2_NAME="Hopper-2"
GROUP_2_SERVERS="
https://www.roblox.com/share?code=bf1119991b6de44095f6d723c0c36b8f&type=Server
https://www.roblox.com/share?code=fdbe4ab807567b4f95421e665e67c405&type=Server
https://www.roblox.com/share?code=bbb4202626bc2249ab7b039f29d605b5&type=Server
https://www.roblox.com/share?code=82e476945d634e4cab00df497f5df17a&type=Server
https://www.roblox.com/share?code=78d5e93f850a084a94aee7c0cfea589e&type=Server
https://www.roblox.com/share?code=4c4851dbcf3527418da94276b931a65d&type=Server
https://www.roblox.com/share?code=d25df99f0234204d8213d797421da886&type=Server
https://www.roblox.com/share?code=1a8665a787c25545bc4bda68b34d5f51&type=Server
https://www.roblox.com/share?code=b58e0eca10f0df428be69da9ff28406b&type=Server
https://www.roblox.com/share?code=f3ca51f023881440ac955404812590c0&type=Server
https://www.roblox.com/share?code=a2ac77a2fa3a3c48b8dcea71deb6dd7a&type=Server
https://www.roblox.com/share?code=006626b5663da749b9b5e12957fdef44&type=Server
https://www.roblox.com/share?code=55b207aacf695447a81548825e50cdff&type=Server
https://www.roblox.com/share?code=9d5e813a50433843a1435d2819c45f6f&type=Server
https://www.roblox.com/share?code=8b7417b278721144a6e36eef46174920&type=Server
https://www.roblox.com/share?code=9e1da6c946c29b44b50000b5d1e488c1&type=Server
https://www.roblox.com/share?code=1270ffcdfdbfb746b6a812735751130a&type=Server
https://www.roblox.com/share?code=73b8d4ab8a2de34d81f72a2ffc85f467&type=Server
https://www.roblox.com/share?code=c7298fe6229e804d8d4dec93f688d7ea&type=Server
https://www.roblox.com/share?code=742dffa59303e14ab5e8041af8fc268b&type=Server
https://www.roblox.com/share?code=6e2a5bb951487c448d08fd04587d9df5&type=Server
https://www.roblox.com/share?code=c0a25739fa7d1a4aad026c5fc6ab0cc9&type=Server
https://www.roblox.com/share?code=0110500be229f4499e6ea4a3a973af8d&type=Server
https://www.roblox.com/share?code=41eebfa30dff5b48a7813b7a5fc92359&type=Server
https://www.roblox.com/share?code=dd095320549ca64bae23c6b4a288370c&type=Server
https://www.roblox.com/share?code=272535803c522f42b216c3daeac96c9d&type=Server
https://www.roblox.com/share?code=5057498e02439d4bbf01186958863829&type=Server
https://www.roblox.com/share?code=bfa36298647d1745b6524c0c175e7cb7&type=Server
https://www.roblox.com/share?code=cb0c8ea50712834c9f9e130dc1d7f35c&type=Server
https://www.roblox.com/share?code=9840d68e35d6834aa0f4fd5d0d0a5c2a&type=Server
https://www.roblox.com/share?code=f66a544a49e1284c8cf54aa6dd063904&type=Server
https://www.roblox.com/share?code=a69d2463d5a8b946b285d85ada986132&type=Server
https://www.roblox.com/share?code=da35f131d358214ca1fe853ce750016a&type=Server
https://www.roblox.com/share?code=938bd344be5c8540a9a93342f9ac43d5&type=Server
https://www.roblox.com/share?code=c8461aed1ca7214bb39bf25658da1f71&type=Server
https://www.roblox.com/share?code=3c5086c314789e4fa6cba22365297324&type=Server
https://www.roblox.com/share?code=9d3b50eb210dd5409a269a89810b4e59&type=Server
https://www.roblox.com/share?code=9bf1b6e12cd4ec4a8129e182ee3c177b&type=Server
https://www.roblox.com/share?code=aa4d2967f803b54ea2db031569c0bcf5&type=Server
https://www.roblox.com/share?code=c9b5ed981053f846b83fd00cffaf9c26&type=Server
https://www.roblox.com/share?code=5c5e495ea8f06d4f943f43515ca89e6c&type=Server
https://www.roblox.com/share?code=66ba406e2736b9459933f38c95c19126&type=Server
https://www.roblox.com/share?code=530bce6d5d13324ca07374f8ab302fa8&type=Server
https://www.roblox.com/share?code=029b1025266c5045bff264c5bcf0a1c3&type=Server
https://www.roblox.com/share?code=89452930d1f408498bc464ee90b48546&type=Server
https://www.roblox.com/share?code=8e32b8bdedd8774e968c7d1973100418&type=Server
https://www.roblox.com/share?code=16086c0eb6c82a43bc873ff90b1593f0&type=Server
https://www.roblox.com/share?code=a1becc31dcb9e14dbe5f9fa222e50ec0&type=Server
https://www.roblox.com/share?code=69815c56ca587a45bdddafcfa099df4a&type=Server
https://www.roblox.com/share?code=dab883134f48844c814b24975cd78589&type=Server
https://www.roblox.com/share?code=6fc4144d5ed05b4fa8bd3edf682b3f40&type=Server
https://www.roblox.com/share?code=92f61b5fb70a2541bf5573b57f2fd9a5&type=Server
https://www.roblox.com/share?code=081d2854b29f2045bdd31353f7d40293&type=Server
https://www.roblox.com/share?code=103b90743503c449a21095f264514166&type=Server
https://www.roblox.com/share?code=d1b2448c864e3d468b75421ec899776e&type=Server
https://www.roblox.com/share?code=04218d00b5f7074bae849b60030b85a0&type=Server
https://www.roblox.com/share?code=9c7befe094a62b4385ad2d2cff539a45&type=Server
https://www.roblox.com/share?code=3f41369807fa28428989cd0b19a7bcd3&type=Server
https://www.roblox.com/share?code=fb4fa677d2e03140bf9bfb5a1c0d7621&type=Server
https://www.roblox.com/share?code=340687815ff27648ab91e1de7bfab130&type=Server
"

GROUP_3_NAME="Hopper-3"
GROUP_3_SERVERS="
https://www.roblox.com/share?code=340687815ff27648ab91e1de7bfab130&type=Server
https://www.roblox.com/share?code=fb4fa677d2e03140bf9bfb5a1c0d7621&type=Server
https://www.roblox.com/share?code=3f41369807fa28428989cd0b19a7bcd3&type=Server
https://www.roblox.com/share?code=9c7befe094a62b4385ad2d2cff539a45&type=Server
https://www.roblox.com/share?code=04218d00b5f7074bae849b60030b85a0&type=Server
https://www.roblox.com/share?code=d1b2448c864e3d468b75421ec899776e&type=Server
https://www.roblox.com/share?code=103b90743503c449a21095f264514166&type=Server
https://www.roblox.com/share?code=081d2854b29f2045bdd31353f7d40293&type=Server
https://www.roblox.com/share?code=92f61b5fb70a2541bf5573b57f2fd9a5&type=Server
https://www.roblox.com/share?code=6fc4144d5ed05b4fa8bd3edf682b3f40&type=Server
https://www.roblox.com/share?code=dab883134f48844c814b24975cd78589&type=Server
https://www.roblox.com/share?code=69815c56ca587a45bdddafcfa099df4a&type=Server
https://www.roblox.com/share?code=a1becc31dcb9e14dbe5f9fa222e50ec0&type=Server
https://www.roblox.com/share?code=16086c0eb6c82a43bc873ff90b1593f0&type=Server
https://www.roblox.com/share?code=8e32b8bdedd8774e968c7d1973100418&type=Server
"

GROUP_4_NAME="Hopper-4"
GROUP_4_SERVERS="
https://www.roblox.com/share?code=89452930d1f408498bc464ee90b48546&type=Server
https://www.roblox.com/share?code=029b1025266c5045bff264c5bcf0a1c3&type=Server
https://www.roblox.com/share?code=530bce6d5d13324ca07374f8ab302fa8&type=Server
https://www.roblox.com/share?code=66ba406e2736b9459933f38c95c19126&type=Server
https://www.roblox.com/share?code=5c5e495ea8f06d4f943f43515ca89e6c&type=Server
https://www.roblox.com/share?code=c9b5ed981053f846b83fd00cffaf9c26&type=Server
https://www.roblox.com/share?code=aa4d2967f803b54ea2db031569c0bcf5&type=Server
https://www.roblox.com/share?code=9bf1b6e12cd4ec4a8129e182ee3c177b&type=Server
https://www.roblox.com/share?code=9d3b50eb210dd5409a269a89810b4e59&type=Server
https://www.roblox.com/share?code=3c5086c314789e4fa6cba22365297324&type=Server
https://www.roblox.com/share?code=c8461aed1ca7214bb39bf25658da1f71&type=Server
https://www.roblox.com/share?code=938bd344be5c8540a9a93342f9ac43d5&type=Server
https://www.roblox.com/share?code=da35f131d358214ca1fe853ce750016a&type=Server
https://www.roblox.com/share?code=a69d2463d5a8b946b285d85ada986132&type=Server
https://www.roblox.com/share?code=f66a544a49e1284c8cf54aa6dd063904&type=Server
"
GROUP_5_NAME="GaG2"
GROUP_5_SERVERS="
https://www.roblox.com/share?code=ea66401508d25d40a58aeeee7f1b415a&type=Server
"
# Environment overrides; webhook notifications are enabled by default.
HOP_DELAY=${HOP_DELAY:-500}
HOME_DELAY=${HOME_DELAY:-2}
LAUNCH_DELAY=${LAUNCH_DELAY:-8}
RETRY_DELAY=${RETRY_DELAY:-3}
MAX_RETRIES=${MAX_RETRIES:-3}
WEBHOOK_URL=${WEBHOOK_URL:-"https://discord.com/api/webhooks/1484573967997206678/Tpix_g8c4U-uaknycIFNUZ3t5UN26rzOq6DNimebAjecDtAdDzwJhAXLZUKRcfwAzZXF"}

log() { printf '%s\n' "$*"; }
fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
usage() {
  cat <<'HELP'
Usage: bash Hopper.sh [--group 1-5] [--once] [--dry-run] [--notify | --no-notify]
  --group N   Select a group without prompting.
  --once      Process the selected list once, then exit.
  --dry-run   Show server order without Android commands, waits, or webhooks.
  --notify    Enable Discord notifications (default; requires jq/curl).
  --no-notify Disable Discord notifications.
Environment: HOP_DELAY=500 HOME_DELAY=2 LAUNCH_DELAY=8 RETRY_DELAY=3 MAX_RETRIES=3
Foreground detection confirms only that Roblox is visible, not a server join.
HELP
}

send_webhook() {
  (( notify && ! dry_run )) || return 0
  local payload
  payload=$(jq -cn --arg content "$1" '{content:$content,allowed_mentions:{parse:[]}}') || {
    log 'Warning: could not encode notification.' >&2
    return 0
  }
  # Do not retry POSTs: an ambiguous timeout could otherwise duplicate messages.
  if ! curl --silent --fail --connect-timeout 3 --max-time 5 \
    -H 'Content-Type: application/json' --data "$payload" \
    "$WEBHOOK_URL" >/dev/null 2>&1; then
    log 'Warning: webhook delivery failed; continuing.' >&2
  fi
}

is_roblox_foreground() {
  local activity
  activity=$("$dumpsys_cmd" activity activities 2>/dev/null) || return 1
  # Android versions differ in the name of the resumed-activity field.
  printf '%s\n' "$activity" |
    grep -E '(mResumedActivity|topResumedActivity)' |
    grep -Eq 'com\.roblox\.client/'
}

main() {
  local group='' once=0 dry_run=0 notify=1 option value
  while (( $# )); do
    case "$1" in
      --group)
        (( $# >= 2 )) || fail '--group needs a number.'
        group=$2; shift 2 ;;
      --once) once=1; shift ;;
      --dry-run) dry_run=1; shift ;;
      --notify) notify=1; shift ;;
      --no-notify) notify=0; shift ;;
      -h|--help) usage; return 0 ;;
      *) fail "Unknown option: $1" ;;
    esac
  done

  for option in HOP_DELAY HOME_DELAY LAUNCH_DELAY RETRY_DELAY MAX_RETRIES; do
    value=${!option}
    [[ $value =~ ^[0-9]{1,6}$ ]] || fail "$option must be an integer from 0 to 999999."
    printf -v "$option" '%d' "$((10#$value))"
  done
  (( MAX_RETRIES > 0 )) || fail 'MAX_RETRIES must be at least 1.'

  if [[ -z $group ]]; then
    log 'Select a group:'
    local n name_var
    for n in {1..5}; do
      name_var="GROUP_${n}_NAME"
      printf '%s) %s\n' "$n" "${!name_var}"
    done
    while true; do
      read -r -p 'Enter group number (1-5): ' group || fail 'No selection received. Use --group N.'
      [[ $group =~ ^[1-5]$ ]] && break
      log 'Invalid selection. Enter 1 through 5.'
    done
  fi
  [[ $group =~ ^[1-5]$ ]] || fail 'Group must be 1 through 5.'
  local name_var="GROUP_${group}_NAME" servers_var="GROUP_${group}_SERVERS"
  local group_name=${!name_var} server
  local -a servers=()
  while IFS= read -r server; do
    server=${server%$'\r'}
    [[ $server =~ ^[[:space:]]*$ ]] && continue
    [[ $server =~ ^https://www\.roblox\.com/share\?code=[[:alnum:]]+\&type=Server$ ]] || fail 'Invalid server URL in preset.'
    servers+=("$server")
  done <<< "${!servers_var}"
  local total=${#servers[@]} index attempt visible failures=0
  local inspect_activity=0 dumpsys_cmd='' activity
  (( total > 0 )) || fail 'Selected group has no servers.'

  if (( ! dry_run )); then
    for option in am grep sleep; do
      command -v "$option" >/dev/null 2>&1 || fail "Missing command: $option. Run on Android in Termux."
    done
    # A permission denial may be printed with a successful exit status.
    dumpsys_cmd=$(command -v dumpsys 2>/dev/null) || dumpsys_cmd=''
    if [[ -z $dumpsys_cmd && -x /system/bin/dumpsys ]]; then
      dumpsys_cmd=/system/bin/dumpsys
    fi
    if [[ -n $dumpsys_cmd ]] && activity=$("$dumpsys_cmd" activity activities 2>&1); then
      if [[ $activity != *'Permission Denial'* && $activity != *'Permission denied'* ]] &&
        printf '%s\n' "$activity" | grep -Eq '(mResumedActivity|topResumedActivity)'; then
        inspect_activity=1
      fi
    fi
    if (( ! inspect_activity )); then
      log 'Activity inspection unavailable. Continuing in launch-only mode; foreground and server joins are unverified.'
    fi
    if (( notify )); then
      [[ $WEBHOOK_URL == https://discord.com/api/webhooks/* ]] || fail 'Set WEBHOOK_URL to your Discord webhook URL.'
      for option in curl jq; do
        command -v "$option" >/dev/null 2>&1 || fail "Missing notification dependency: $option"
      done
    fi
  fi

  trap 'printf "\nStopped.\n"; exit 130' INT
  trap 'printf "\nStopped.\n"; exit 143' TERM
  log "Loaded $total servers from [$group_name]"
  send_webhook "[$group_name] Started with $total servers"
  while true; do
    index=0
    for server in "${servers[@]}"; do
      ((index+=1))
      log "[$group_name] Launching ($index/$total)"
      if (( dry_run )); then
        log "$server"
        continue
      fi
      visible=0
      for ((attempt=1; attempt<=MAX_RETRIES; attempt++)); do
        log "Attempt $attempt/$MAX_RETRIES"
        # Reset foreground each time so an old Roblox activity cannot satisfy the check.
        if am start -a android.intent.action.MAIN -c android.intent.category.HOME >/dev/null 2>&1; then
          sleep "$HOME_DELAY"
          if (( ! inspect_activity )) || ! is_roblox_foreground; then
            if am start -a android.intent.action.VIEW -d "$server" >/dev/null 2>&1; then
              sleep "$LAUNCH_DELAY"
              if (( ! inspect_activity )); then
                visible=2
                break
              elif is_roblox_foreground; then
                visible=1
                break
              fi
            fi
          fi
        fi
        log 'Launch could not be confirmed.'
        (( attempt < MAX_RETRIES )) && sleep "$RETRY_DELAY"
      done
      if (( visible )); then
        if (( visible == 1 )); then
          log 'Roblox is in the foreground; server join is unverified.'
          send_webhook "[$group_name] Roblox foreground ($index/$total); server join unverified"
        else
          log 'Launch command sent; foreground and server join are unverified.'
          send_webhook "[$group_name] Launch command sent ($index/$total); foreground and server join unverified"
        fi
        # No final dwell is needed when exiting a single pass.
        if (( ! once || index < total )); then sleep "$HOP_DELAY"; fi
      else
        ((failures+=1))
        log "Failed to bring Roblox to the foreground ($index/$total)."
        send_webhook "[$group_name] Launch failed ($index/$total) after $MAX_RETRIES attempts"
        if (( ! once || index < total )); then sleep "$RETRY_DELAY"; fi
      fi
    done
    (( once || dry_run )) && break
  done
  log "Completed. Failed launches: $failures"
  (( failures == 0 ))
}

# Sourcing allows isolated tests without starting the hopper.
if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@"
fi
